# Download dataset

In [1]:
# Download dataset from Kaggle using kagglehub library
import kagglehub

path = kagglehub.dataset_download("piterfm/milano-cortina-2026-olympic-winter-games")

print("Path to dataset files:", path)

Downloading to /home/thomas/.cache/kagglehub/datasets/piterfm/milano-cortina-2026-olympic-winter-games/11.archive...

100%|██████████| 101k/101k [00:00<00:00, 524kB/s]

Extracting files...

Path to dataset files: /home/thomas/.cache/kagglehub/datasets/piterfm/milano-cortina-2026-olympic-winter-games/versions/11

# Initial dataset investigation

## Athletes

In [ ]:
# Load the dataset using pandas
import pandas as pd

df_athletes = pd.read_csv(path + "/athletes.csv")

In [9]:
df_athletes.shape

(2916, 6)

In [7]:
df_athletes.columns

Index(['code', 'name', 'gender', 'country_code', 'flag_bearer', 'events'], dtype='str')

In [8]:
df_athletes.info()

<class 'pandas.DataFrame'>
RangeIndex: 2916 entries, 0 to 2915
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   code          2916 non-null   int64
 1   name          2916 non-null   str
 2   gender        2916 non-null   str
 3   country_code  2916 non-null   str
 4   flag_bearer   2916 non-null   int64
 5   events        2916 non-null   str
dtypes: int64(2), str(4)
memory usage: 136.8 KB

In [5]:
df_athletes.head()

,code,name,gender,country_code,flag_bearer,events
0,139893,AABREKK Ingrid Bergene,F,NOR,0,"[{'discipline': 'Cross-Country Skiing', 'event..."
1,24464,AAGAARD Mikkel,M,DEN,0,"[{'discipline': 'Ice Hockey', 'event': 'Men'}]"
2,45083,AALTO Antti,M,FIN,0,"[{'discipline': 'Ski Jumping', 'event': ""Men's..."
3,32319,ABATANGELO Aurora,F,ITA,0,"[{'discipline': 'Ice Hockey', 'event': 'Women'}]"
4,4972,ABDI Fayik,M,KSA,0,"[{'discipline': 'Alpine Skiing', 'event': ""Men..."

In [6]:
df_athletes.tail()

,code,name,gender,country_code,flag_bearer,events
2911,25116,ZUMWINKLE Grace,F,USA,0,"[{'discipline': 'Ice Hockey', 'event': 'Women'}]"
2912,44328,ZUNTE Darta,F,EST,0,"[{'discipline': 'Skeleton', 'event': 'Women'}]"
2913,7319,ZURBAY Anabelle,F,IRL,1,"[{'discipline': 'Alpine Skiing', 'event': ""Wom..."
2914,19124,ZURBRIGGEN Anina,F,BUL,0,"[{'discipline': 'Alpine Skiing', 'event': ""Wom..."
2915,23401,ZUREK Damian,M,POL,0,"[{'discipline': 'Speed Skating', 'event': ""Men..."

In [10]:
df_athletes.describe()

                code  flag_bearer
count    2916.000000  2916.000000
mean    36401.582990     0.122085
std     16043.661964     0.470224
min      4098.000000     0.000000
25%     24173.000000     0.000000
50%     39906.500000     0.000000
75%     45897.000000     0.000000
max    170798.000000     3.000000

## Coaches

In [ ]:
# Load the dataset using pandas
import pandas as pd

df_coaches = pd.read_csv(path + "/coaches.csv")

In [ ]:
df_coaches.shape

(50, 7)

In [ ]:
df_coaches.columns

Index(['code', 'name', 'gender', 'country_code', 'nationality', 'function',
       'events'],
      dtype='str')

In [ ]:
df_coaches.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   code          50 non-null     int64
 1   name          50 non-null     str
 2   gender        50 non-null     str
 3   country_code  50 non-null     str
 4   nationality   50 non-null     str
 5   function      50 non-null     str
 6   events        50 non-null     str
dtypes: int64(1), str(6)
memory usage: 2.9 KB

In [ ]:
df_coaches.head()

,code,name,gender,country_code,nationality,function,events
0,50140,BOUCHARD Eric,M,ITA,CAN,Head Coach,"[{'discipline': 'Ice Hockey', 'event': 'Women'}]"
1,50988,CERNOVSKY Vladimir,M,CZE,CZE,Coach,"[{'discipline': 'Curling', 'event': 'Mixed Dou..."
2,49020,CHARETTE Pierre,M,SUI,CAN,Coach,"[{'discipline': 'Curling', 'event': 'Women'}]"
3,53809,COOPER Jon,M,CAN,CAN,Head Coach,"[{'discipline': 'Ice Hockey', 'event': 'Men'}]"
4,49035,de CRUZ Peter,M,SUI,SUI,Coach,"[{'discipline': 'Curling', 'event': 'Mixed Dou..."

In [ ]:
df_coaches.tail()

,code,name,gender,country_code,nationality,function,events
45,47166,VITOLINS Harijs,M,LAT,LAT,Head Coach,"[{'discipline': 'Ice Hockey', 'event': 'Men'}]"
46,22959,WALSTAD Steffen,M,EST,NOR,Coach,"[{'discipline': 'Curling', 'event': 'Mixed Dou..."
47,53327,WEBSTER Paul,M,CAN,CAN,Coach,"[{'discipline': 'Curling', 'event': 'Men'}]"
48,25178,WROBLEWSKI John,M,USA,USA,Head Coach,"[{'discipline': 'Ice Hockey', 'event': 'Women'}]"
49,39951,ZANG Jialiang,M,CHN,CHN,Coach,"[{'discipline': 'Curling', 'event': 'Women'}]"

In [ ]:
df_coaches.describe()

                code
count      50.000000
mean    41325.620000
std     19130.461623
min     18095.000000
25%     29014.000000
50%     41103.500000
75%     49326.250000
max    149123.000000

## Medallists

In [32]:
# Load the dataset using pandas
import pandas as pd

df_medallists = pd.read_csv(path + "/medallists.csv")

In [33]:
df_medallists.shape

(709, 11)

In [34]:
df_medallists.columns

Index(['date', 'medal_code', 'medal', 'code', 'name', 'gender', 'country_code',
       'country', 'discipline', 'discipline_code', 'event_name'],
      dtype='str')

In [35]:
df_medallists.info()

<class 'pandas.DataFrame'>
RangeIndex: 709 entries, 0 to 708
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date             709 non-null    str
 1   medal_code       709 non-null    int64
 2   medal            709 non-null    str
 3   code             709 non-null    int64
 4   name             709 non-null    str
 5   gender           709 non-null    str
 6   country_code     709 non-null    str
 7   country          709 non-null    str
 8   discipline       709 non-null    str
 9   discipline_code  709 non-null    str
 10  event_name       709 non-null    str
dtypes: int64(2), str(9)
memory usage: 61.1 KB

In [36]:
df_medallists.head()

,date,medal_code,medal,code,name,gender,country_code,country,discipline,discipline_code,event_name
0,2026-02-07,1,GOLD,48729,von ALLMEN Franjo,M,SUI,Switzerland,Alpine Skiing,ALP,Men's Downhill
1,2026-02-07,2,SILVER,25998,FRANZONI Giovanni,M,ITA,Italy,Alpine Skiing,ALP,Men's Downhill
2,2026-02-07,3,BRONZE,26002,PARIS Dominik,M,ITA,Italy,Alpine Skiing,ALP,Men's Downhill
3,2026-02-07,1,GOLD,30739,KARLSSON Frida,F,SWE,Sweden,Cross-Country Skiing,CCS,Women's 10km + 10km Skiathlon
4,2026-02-07,2,SILVER,30707,ANDERSSON Ebba,F,SWE,Sweden,Cross-Country Skiing,CCS,Women's 10km + 10km Skiathlon

In [37]:
df_medallists.tail()

,date,medal_code,medal,code,name,gender,country_code,country,discipline,discipline_code,event_name
704,2026-02-22,2,SILVER,53901,SUZUKI Nick,M,CAN,Canada,Ice Hockey,IHO,Men
705,2026-02-22,2,SILVER,53905,THEODORE Shea,M,CAN,Canada,Ice Hockey,IHO,Men
706,2026-02-22,2,SILVER,53907,THOMPSON Logan,M,CAN,Canada,Ice Hockey,IHO,Men
707,2026-02-22,2,SILVER,53910,TOEWS Devon,M,CAN,Canada,Ice Hockey,IHO,Men
708,2026-02-22,2,SILVER,53914,WILSON Tom,M,CAN,Canada,Ice Hockey,IHO,Men

In [38]:
df_medallists.describe()

       medal_code           code
count  709.000000     709.000000
mean     1.994358   37871.267983
std      0.814745   14925.077758
min      1.000000    6464.000000
25%      1.000000   25029.000000
50%      2.000000   42254.000000
75%      3.000000   48300.000000
max      3.000000  170798.000000

# Quality check

## Athletes

In [11]:
duplicated_rows = df_athletes[df_athletes.duplicated()]
duplicated_rows

Empty DataFrame
Columns: [code, name, gender, country_code, flag_bearer, events]
Index: []

In [12]:
df_athletes.nunique()

code            2916
name            2916
gender             2
country_code      93
flag_bearer        4
events           344
dtype: int64

Complete dataset for athletes. Extra flag bearer info.

## Coaches

In [ ]:
duplicated_rows = df_coaches[df_coaches.duplicated()]
duplicated_rows

Empty DataFrame
Columns: [code, name, gender, country_code, flag_bearer, events]
Index: []

In [30]:
df_coaches.nunique()

code            50
name            50
gender           2
country_code    18
nationality     15
function         2
events           8
dtype: int64

Incomplete dataset for coaches (only 50).

## Medallists

In [39]:
duplicated_rows = df_medallists[df_medallists.duplicated()]
duplicated_rows

Empty DataFrame
Columns: [date, medal_code, medal, code, name, gender, country_code, country, discipline, discipline_code, event_name]
Index: []

In [40]:
df_medallists.nunique()

date                16
medal_code           3
medal                3
code               534
name               534
gender               2
country_code        30
country             30
discipline          16
discipline_code     16
event_name         104
dtype: int64

Looks like 31 medals are missing. Can fill dataset by hand.

# Ideas of exploration

Local map with events clickable to enter new page dedicated to sports which took place there

Look into past winter olympics and see dynasties/new comers in Milan 2026

Look into visitors/economical/environmentals impacts

Do animation where we see dots arriving to the games (1 dot per athlete): start animation

Classic medal race

Flag bearers (legendary figures)

Are coaches old legends? And do they work for their country OR the best country in the domain OR rich country.

Men vs Women in discipline per country

Don't forget to cite dataset!