# Download dataset

In [ ]:
# Download dataset from Kaggle using kagglehub library
import kagglehub

path = kagglehub.dataset_download("likithagedipudi/war-economic-and-livelihood-impact-dataset")

print("Path to dataset files:", path)

Downloading to /home/thomas/.cache/kagglehub/datasets/likithagedipudi/war-economic-and-livelihood-impact-dataset/1.archive...

100%|██████████| 6.10M/6.10M [00:00<00:00, 6.69MB/s]

Extracting files...

Path to dataset files: /home/thomas/.cache/kagglehub/datasets/likithagedipudi/war-economic-and-livelihood-impact-dataset/versions/1

# Initial dataset investigation

In [ ]:
# Load the dataset using pandas
import pandas as pd

df = pd.read_csv(path + "/war_economic_impact_dataset.csv")

In [ ]:
df.head()

,Conflict_Name,Conflict_Type,Region,Start_Year,End_Year,Status,Primary_Country,Pre_War_Unemployment_%,During_War_Unemployment_%,Unemployment_Spike_Percentage_Points,...,Inflation_Rate_%,Currency_Devaluation_%,Cost_of_War_USD,Estimated_Reconstruction_Cost_USD,Informal_Economy_Size_Pre_War_%,Informal_Economy_Size_During_War_%,Black_Market_Activity_Level,Primary_Black_Market_Goods,Currency_Black_Market_Rate_Gap_%,War_Profiteering_Documented
0,WWII (Japan),World War,East Asia,1939,1945,Resolved,Japan,7.49,21.78,14.29,...,97.41,170.33,106957216228,209054555175,15.50,27.09,High,food,10.50,No
1,Israel-Hamas War,Asymmetric War,Middle East,2023,2026,Ongoing,Palestine (Gaza),8.18,23.00,14.82,...,73.68,41.97,304164881098,585915946162,11.95,34.76,Dominant,fuel,19.31,No
2,Syrian Civil War,Civil War,Middle East,2011,2026,Ongoing,Syria,12.70,36.46,23.76,...,69.35,53.91,484822729254,1666739121273,38.18,90.00,Moderate,"water, weapons, currency",298.95,No
3,WWII (Germany),World War,Europe,1939,1945,Resolved,Germany,14.06,17.83,3.77,...,36.92,48.51,71321188262,250015887113,12.24,36.42,Moderate,"currency, medicine, weapons",15.44,No
4,Afghanistan War,Interstate/Counter-insurgency,South Asia,2001,2021,Resolved,Afghanistan,5.38,5.98,0.59,...,52.62,31.32,156180178536,361238241031,31.89,74.86,Dominant,medicine,443.61,Yes

In [8]:
df.columns

Index(['Conflict_Name', 'Conflict_Type', 'Region', 'Start_Year', 'End_Year',
       'Status', 'Primary_Country', 'Pre_War_Unemployment_%',
       'During_War_Unemployment_%', 'Unemployment_Spike_Percentage_Points',
       'Most_Affected_Sector', 'Youth_Unemployment_Change_%',
       'Pre_War_Poverty_Rate_%', 'During_War_Poverty_Rate_%',
       'Extreme_Poverty_Rate_%', 'Food_Insecurity_Rate_%',
       'Households_Fallen_Into_Poverty_Estimate', 'GDP_Change_%',
       'Inflation_Rate_%', 'Currency_Devaluation_%', 'Cost_of_War_USD',
       'Estimated_Reconstruction_Cost_USD', 'Informal_Economy_Size_Pre_War_%',
       'Informal_Economy_Size_During_War_%', 'Black_Market_Activity_Level',
       'Primary_Black_Market_Goods', 'Currency_Black_Market_Rate_Gap_%',
       'War_Profiteering_Documented'],
      dtype='str')

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 28 columns):
 #   Column                                   Non-Null Count   Dtype
---  ------                                   --------------   -----
 0   Conflict_Name                            100000 non-null  str
 1   Conflict_Type                            100000 non-null  str
 2   Region                                   100000 non-null  str
 3   Start_Year                               100000 non-null  int64
 4   End_Year                                 100000 non-null  int64
 5   Status                                   100000 non-null  str
 6   Primary_Country                          100000 non-null  str
 7   Pre_War_Unemployment_%                   100000 non-null  float64
 8   During_War_Unemployment_%                100000 non-null  float64
 9   Unemployment_Spike_Percentage_Points     100000 non-null  float64
 10  Most_Affected_Sector                     100000 non-null  str
 11  Youth_Unemployment_Change_%              100000 non-null  float64
 12  Pre_War_Poverty_Rate_%                   100000 non-null  float64
 13  During_War_Poverty_Rate_%                100000 non-null  float64
 14  Extreme_Poverty_Rate_%                   100000 non-null  float64
 15  Food_Insecurity_Rate_%                   100000 non-null  float64
 16  Households_Fallen_Into_Poverty_Estimate  100000 non-null  int64
 17  GDP_Change_%                             100000 non-null  float64
 18  Inflation_Rate_%                         100000 non-null  float64
 19  Currency_Devaluation_%                   100000 non-null  float64
 20  Cost_of_War_USD                          100000 non-null  int64
 21  Estimated_Reconstruction_Cost_USD        100000 non-null  int64
 22  Informal_Economy_Size_Pre_War_%          100000 non-null  float64
 23  Informal_Economy_Size_During_War_%       100000 non-null  float64
 24  Black_Market_Activity_Level              100000 non-null  str
 25  Primary_Black_Market_Goods               100000 non-null  str
 26  Currency_Black_Market_Rate_Gap_%         100000 non-null  float64
 27  War_Profiteering_Documented              100000 non-null  str
dtypes: float64(14), int64(5), str(9)
memory usage: 21.4 MB

In [9]:
df.shape

(100000, 28)

In [11]:
df.describe()

,Start_Year,End_Year,Pre_War_Unemployment_%,During_War_Unemployment_%,Unemployment_Spike_Percentage_Points,Youth_Unemployment_Change_%,Pre_War_Poverty_Rate_%,During_War_Poverty_Rate_%,Extreme_Poverty_Rate_%,Food_Insecurity_Rate_%,Households_Fallen_Into_Poverty_Estimate,GDP_Change_%,Inflation_Rate_%,Currency_Devaluation_%,Cost_of_War_USD,Estimated_Reconstruction_Cost_USD,Informal_Economy_Size_Pre_War_%,Informal_Economy_Size_During_War_%,Currency_Black_Market_Rate_Gap_%
count,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,1.000000e+05,100000.000000,100000.000000,100000.000000,1.000000e+05,1.000000e+05,100000.000000,100000.000000,100000.000000
mean,1999.401340,2009.039940,9.017027,22.625199,13.608181,17.686763,17.518820,29.077185,14.553542,20.351211,1.597617e+05,-31.614770,69.945965,87.580570,2.507148e+11,6.895004e+11,25.002639,51.783920,126.181130
std,29.957153,30.552183,3.458406,13.818295,11.960175,15.678211,7.217439,13.000781,7.487060,9.790643,9.355617e+05,18.120243,35.045196,55.632842,1.436970e+11,4.471766e+11,8.648263,21.266786,156.324982
min,1939.000000,1945.000000,3.000000,3.360000,0.320000,0.360000,5.000000,5.400000,1.840000,3.100000,1.000000e+00,-85.000000,0.030000,0.030000,1.001111e+09,1.617224e+09,10.000000,12.140000,0.000000
25%,1996.000000,2011.000000,6.030000,12.780000,5.330000,6.860000,11.260000,20.030000,9.270000,13.490000,5.710750e+03,-42.210000,42.710000,45.110000,1.266235e+11,3.239366e+11,17.520000,34.420000,9.330000
50%,2011.000000,2026.000000,9.020000,19.480000,10.220000,13.245000,17.520000,27.630000,13.200000,18.800000,2.210450e+04,-29.700000,69.290000,76.680000,2.501850e+11,6.367629e+11,25.010000,49.190000,18.760000
75%,2022.000000,2026.000000,12.000000,28.800000,17.890000,23.270000,23.790000,35.290000,18.250000,25.200000,8.439800e+04,-17.337500,94.800000,120.460000,3.750452e+11,9.934733e+11,32.490000,67.820000,241.432500
max,2025.000000,2026.000000,15.000000,89.400000,74.470000,108.710000,30.000000,98.000000,68.490000,86.320000,9.928908e+07,-5.000000,295.560000,528.400000,4.999992e+11,1.997802e+12,40.000000,90.000000,500.000000

## Quality check

In [13]:
duplicated_rows = df[df.duplicated()]
duplicated_rows

Empty DataFrame
Columns: [Conflict_Name, Conflict_Type, Region, Start_Year, End_Year, Status, Primary_Country, Pre_War_Unemployment_%, During_War_Unemployment_%, Unemployment_Spike_Percentage_Points, Most_Affected_Sector, Youth_Unemployment_Change_%, Pre_War_Poverty_Rate_%, During_War_Poverty_Rate_%, Extreme_Poverty_Rate_%, Food_Insecurity_Rate_%, Households_Fallen_Into_Poverty_Estimate, GDP_Change_%, Inflation_Rate_%, Currency_Devaluation_%, Cost_of_War_USD, Estimated_Reconstruction_Cost_USD, Informal_Economy_Size_Pre_War_%, Informal_Economy_Size_During_War_%, Black_Market_Activity_Level, Primary_Black_Market_Goods, Currency_Black_Market_Rate_Gap_%, War_Profiteering_Documented]
Index: []

[0 rows x 28 columns]

In [14]:
df.nunique()

Conflict_Name                                  11
Conflict_Type                                   5
Region                                          5
Start_Year                                     10
End_Year                                        5
Status                                          2
Primary_Country                                13
Pre_War_Unemployment_%                       1201
During_War_Unemployment_%                    7188
Unemployment_Spike_Percentage_Points         6226
Most_Affected_Sector                            6
Youth_Unemployment_Change_%                  7786
Pre_War_Poverty_Rate_%                       2501
During_War_Poverty_Rate_%                    7116
Extreme_Poverty_Rate_%                       4432
Food_Insecurity_Rate_%                       5568
Households_Fallen_Into_Poverty_Estimate     62109
GDP_Change_%                                 6933
Inflation_Rate_%                            15512
Currency_Devaluation_%                      21993
Cost_of_War_USD                            100000
Estimated_Reconstruction_Cost_USD          100000
Informal_Economy_Size_Pre_War_%              3001
Informal_Economy_Size_During_War_%           7719
Black_Market_Activity_Level                     4
Primary_Black_Market_Goods                    156
Currency_Black_Market_Rate_Gap_%            31806
War_Profiteering_Documented                     2
dtype: int64

ISSUES: Only 11 distinct conflicts. 10000 synthetic but good data. Hence not enough conflict and too synthetic.

### Ideas of exploration

World map with exploding circles for conflicts over time and other animation for end of conflict (clashing swords vs. doves)

Investigate unemployement rate vs. war likely

Investigate conflict types

Cost of war(time)

Black market(region, time)

One war leads to another rapidly?